apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: blogomatic
  - name: blogomatic-config

resources:
  - ./blogomatic/deployment.yaml
  - ./blogomatic/service.yaml
