apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpine

images:
- name: timoniersystems/blogomatic
  newName: timoniersystems/blogomatic
  newTag: alpine-multistage-2f07e41

configMapGenerator:
- behavior: replace
  files:
  - blogomatic/config.yaml
  name: blogomatic-config

resources:
- ./blogomatic/ingress.yaml
- ./blogomatic/sealed-secret.yaml
- ../../base/

patches:
- path: ./blogomatic/configmap.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: blogomatic
  path: blogomatic/deployment-patch.yaml
