apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blogomatic.fullname" . }}-config-ckmhth7845
  labels:
  {{- include "blogomatic.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.configCkmhth7845.configYaml | toYaml | indent 1 }}