apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blogomatic.fullname" . }}-blogomatic
  labels:
    app: blogomatic
  {{- include "blogomatic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.blogomatic.replicas }}
  selector:
    matchLabels:
      app: blogomatic
    {{- include "blogomatic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: blogomatic
      {{- include "blogomatic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "blogomatic.fullname" . }}-mtb9fck787
        image: {{ .Values.blogomatic.blogomatic.image.repository }}:{{ .Values.blogomatic.blogomatic.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.blogomatic.blogomatic.imagePullPolicy }}
        name: blogomatic
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {{- toYaml .Values.blogomatic.blogomatic.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.blogomatic.blogomatic.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /data
          name: sqlite-volume
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: {{ include "blogomatic.fullname" . }}-sqlite-pvc
      - configMap:
          name: {{ include "blogomatic.fullname" . }}-config-ckmhth7845
        name: blogomatic-config-file