apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogomatic
spec:
  template:
    spec:
      containers:
        - name: blogomatic
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          volumeMounts:
          - name: sqlite-volume
            mountPath: /data
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc
