apiVersion: v1
kind: Service
metadata:
  name: blogomatic
  labels:
    app: blogomatic
spec:
  selector:
    app: blogomatic
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
