apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-repl-codepraxis-tls
spec:
  # Secret names are always required.
  secretName: postgres-repl-codepraxis-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - codepraxis-dev
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: _crunchyrepl
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - _crunchyrepl
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
