name: docker-build-binary-and-insert

on:
  push:
    # tags:        
    #   - v*.*.*
    branches:
     - main
    # paths:
    #   - "src/**"
  workflow_call:

jobs:
  app-build-debian-bullseye:
    uses: ./.github/workflows/generic-app-build-workflow.yml
    with:
      build_dir: 'bin'
      cosign_blob_name: ${{ github.repository }}-debian-bullseye
      docker_build_image: 'ghcr.io/codepraxis-io/blogomatic:debian-cicd'
    #secrets: inherit
    secrets: 
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

  app-docker-distroless-debian-bullseye:
    uses: ./.github/workflows/generic-app-docker-workflow.yml
    needs: ['app-build-debian-bullseye']
    with:
      build_dir: 'bin'
      cosign_blob_name: ${{ github.repository }}-debian-bullseye
      docker_image_name: ${{ github.repository }}
      docker_image_tag_suffix: 'distroless'
      dockerfile_name: 'Dockerfile.distroless'
      dockerfile_scanner: 'semgrep'
      #stop_on_critical_vulns: 'true'
      verify_base_image_signature: 'false'
    #secrets: inherit
    secrets: 
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

  # app-build-alpine:
  #   uses: codepraxis-io/github-actions/.github/workflows/app-build-workflow.yml@main
  #   with:
  #     build_dir: 'venv'
  #     cosign_blob_name: ${{ github.repository }}
  #     docker_build_image: 'ghcr.io/codepraxis-io/alpine3.16:python3.10-build'
  #   #secrets: inherit
  #   secrets: 
  #     destination_registry_username: ${{secrets.GHCR_USERNAME}}
  #     destination_registry_password: ${{secrets.GHCR_TOKEN}}
  #     cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
  #     cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
  #     cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

  # app-docker-alpine-316:
  #   uses: codepraxis-io/github-actions/.github/workflows/app-docker-workflow.yml@main
  #   needs: ['app-build-alpine']
  #   with:
  #     build_dir: 'venv'
  #     cosign_blob_name: ${{ github.repository }}
  #     docker_image_name: ${{ github.repository }}
  #     docker_image_tag_suffix: 'alpine3.16-python3.10'
  #     docker_run_image: 'ghcr.io/codepraxis-io/alpine3.16:python3.10-run'
  #     docker_image_scanner: 'grype'
  #   #secrets: inherit
  #   secrets: 
  #     destination_registry_username: ${{secrets.GHCR_USERNAME}}
  #     destination_registry_password: ${{secrets.GHCR_TOKEN}}
  #     cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
  #     cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
  #     cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

